baseurl = "https://davic1uo.github.io/"
title = "luo blog posts"
languageCode = "en-us"
disqusShortname = "luo-me"
MetaDataFormat = "toml"
googleAnalytics = "UA-7131036-1"

[author]
    name = "luo"
[taxonomies]
  category = "categories"
  tag = "tags"

